apiVersion: v1
kind: Service
metadata:
  name: backend-service-1
spec:
  selector:
    app: backend-service-1
  ports:
    - protocol: TCP
      port: 80        # Port to expose on the Service
      targetPort: 3001 # Port on the container
      nodePort: 30080 # NodePort to expose (optional; Kubernetes will auto-assign if omitted)
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service-2
spec:
  selector:
    app: backend-service-2
  ports:
    - protocol: TCP
      port: 81        # Port to expose on the Service
      targetPort: 3002 # Port on the container
      nodePort: 30081 # NodePort to expose (optional; Kubernetes will auto-assign if omitted)
  type: NodePort
