apiVersion: v1
kind: Service
metadata:
  name: backend-service-1
spec:
  selector:
    app: backend-service-1
  ports:
    - protocol: TCP
      port: 80        # Port to expose on the Service
      targetPort: 80  # Port on the container (fixed to match Deployment)
      nodePort: 30080 # NodePort to expose (optional; Kubernetes will auto-assign if omitted)
  type: NodePort
